name: Electron Build MacOS

on:
  push:
    paths:
      - 'package.json'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Test app
      run: npm run test

    - name: Build app
      run: npm run dist

    - name: Release app
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/*.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

